In [1]:
# ============================================================
# Comparar_enlaces_ARIMA_h.py — v1.2  (celda de Jupyter, NIVEL HORARIO)
# MAE, RMSE, MAPE y WAPE por enlace de cada arquitectura horaria frente a ARIMA (T+1 h).
#   - DATASET = "abilene" o "brain" (rutas y TRIGGER de cada uno).
#   - Una tabla por métrica, ventana W (24, 168) y modo (A, B).
#   - Mismos instantes para todos los modelos (inner join con ARIMA).
#   - Una tabla por métrica, horizonte y modo: filas = enlaces, columnas = ARIMA y
#     Arch1–4; el mejor de cada enlace en negrita.
#   - Al final de cada tabla:
#       GLOBAL         → media de los enlaces (MAE, RMSE, MAPE); WAPE = Σ|e| / Σ real
#       % gana ARIMA   → % de enlaces en los que la arquitectura tiene menor métrica
#   - Formato: > 999 → 1.3e3 ; 99 … 999 → entero ; < 99 → un decimal.
#   - GUARDAR_CSV = True guarda cada tabla (valores sin formato) en DIR_SALIDA.
# ============================================================
import os
import numpy as np
import pandas as pd
from decimal import Decimal, ROUND_HALF_UP
from IPython.display import display, HTML

DATASET = "abilene"          # "abilene" | "brain"

if DATASET == "abilene":
    ROOT_RESULTS = "Results_horas_abilene"
    DIR_BASE     = "Results_horas_abilene/results_baselines_1h"
    TRIGGER      = 0.001                               # todos los instantes
else:
    ROOT_RESULTS = "Results_horas"
    DIR_BASE     = "Results_horas/results_baselines_1h"
    TRIGGER      = 1000

COL_ARIMA   = lambda W: "ARIMA_t+1"                    # T+1 h

CARPETA     = "results_Arq{ID}_1h_{MODO}_W{H}"         # aquí {H} es la ventana W
COL_PRED    = "Prediccion"
IDS         = [1, 2, 3, 4]
HORIZONTES  = [24, 168]                                # ventanas W (horas)
MODOS       = ["A", "B"]
METRICAS    = ["MAE", "RMSE", "MAPE", "WAPE"]
GUARDAR_CSV = False
DIR_SALIDA  = f"Tablas_enlaces_h_{DATASET}"


def _red(x, dec):
    return Decimal(repr(float(x))).quantize(Decimal(1).scaleb(-dec), rounding=ROUND_HALF_UP)


def val(v):
    if pd.isna(v):
        return "--"
    if v > 999:
        e = int(np.floor(np.log10(v)))
        m = _red(v / 10 ** e, 1)
        if m >= 10:
            m, e = _red(m / 10, 1), e + 1
        return f"{m}e{e}"
    if v >= 99:
        return str(int(_red(v, 0)))
    return f"{_red(v, 1)}"


def leer(ID, H, MODO):
    d = os.path.join(ROOT_RESULTS, CARPETA.format(ID=ID, H=H, MODO=MODO))
    if not os.path.isdir(d):
        print(f"   ⏭  Arch{ID} W{H} {MODO}: no existe {d}")
        return {}
    pref = "test_" + os.path.basename(d).removeprefix("results_") + "_"
    return {f[len(pref):-4]: os.path.join(d, f) for f in os.listdir(d)
            if f.startswith(pref) and f.endswith(".csv")}


def metricas(y, p):
    err = y - p
    m = y > 0
    return {"MAE": np.abs(err).mean(), "RMSE": np.sqrt((err ** 2).mean()),
            "MAPE": np.mean(np.abs(err[m]) / y[m]) * 100 if m.any() else np.nan,
            "WAPE": np.abs(err).sum() / y.sum() * 100}


def tabla(H):
    """Cada arquitectura con los enlaces que tenga. Para cada enlace y arquitectura,
    la arquitectura y ARIMA se evalúan en los mismos instantes (arquitectura ∩ ARIMA)."""
    arqs = {(ID, MODO): a for ID in IDS for MODO in MODOS if (a := leer(ID, H, MODO))}
    if not arqs:
        return None, None, None
    modelos = ["ARIMA"] + [f"Arch{ID}_{MODO}" for (ID, MODO) in arqs]
    filas = []
    se = {m: 0.0 for m in modelos}; sy = {m: 0.0 for m in modelos}
    gana = {m: [] for m in modelos[1:]}
    for e in sorted(set.union(*[set(a) for a in arqs.values()])):
        fb = os.path.join(DIR_BASE, f"test_results_{e}_baselines.csv")
        if not os.path.exists(fb):
            continue
        b = pd.read_csv(fb, parse_dates=["timestamp"]).set_index("timestamp")
        if COL_ARIMA(H) not in b.columns:
            raise SystemExit(f"❌ {fb} no tiene {COL_ARIMA(H)}; columnas: {list(b.columns)}")
        b = b[[COL_ARIMA(H)]].rename(columns={COL_ARIMA(H): "ARIMA"})
        fila, ts_arima = {"Link": e}, None
        for (ID, MODO), a in arqs.items():
            m = f"Arch{ID}_{MODO}"
            if e not in a:
                continue
            t = pd.read_csv(a[e], parse_dates=["timestamp"]).set_index("timestamp")
            j = t[["Realidad", COL_PRED]].rename(columns={COL_PRED: m}).join(b, how="inner").dropna()
            if TRIGGER is not None:
                j = j[j["Realidad"] > TRIGGER]
            if j.empty:
                continue
            y = j["Realidad"].values
            r, ra = metricas(y, j[m].values), metricas(y, j["ARIMA"].values)
            for met in METRICAS:
                fila[(met, m)] = r[met]
            gana[m].append({met: r[met] < ra[met] for met in METRICAS})
            se[m] += np.abs(y - j[m].values).sum(); sy[m] += y.sum()
            if ts_arima is None:                       # ARIMA de la fila: instantes de la 1.ª arquitectura
                ts_arima = j
        if ts_arima is None:
            continue
        y = ts_arima["Realidad"].values
        r = metricas(y, ts_arima["ARIMA"].values)
        for met in METRICAS:
            fila[(met, "ARIMA")] = r[met]
        se["ARIMA"] += np.abs(y - ts_arima["ARIMA"].values).sum(); sy["ARIMA"] += y.sum()
        filas.append(fila)
    if not filas:
        return None, None, None
    df = pd.DataFrame(filas)
    for m in modelos:
        for met in METRICAS:
            if (met, m) not in df:
                df[(met, m)] = np.nan
    glob = {met: {m: df[(met, m)].mean() for m in modelos} for met in ["MAE", "RMSE", "MAPE"]}
    glob["WAPE"] = {m: 100 * se[m] / sy[m] if sy[m] else np.nan for m in modelos}
    glob["n"] = {m: int(df[("MAE", m)].notna().sum()) for m in modelos}
    glob["gana"] = {m: {met: 100 * np.mean([g[met] for g in gana[m]]) if gana[m] else np.nan
                        for met in METRICAS} for m in modelos[1:]}
    return df, modelos, glob


def mostrar(df, modelos, glob, met, H):
    neg = lambda t, b: f"<b>{t}</b>" if b else t
    filas, crudo = [], []
    for _, r in df.iterrows():
        v = {m: r[(met, m)] for m in modelos}
        hay = {m: x for m, x in v.items() if pd.notna(x)}
        mejor = min(hay, key=hay.get) if hay else None
        filas.append({"Link": r["Link"], **{m: neg(val(v[m]), m == mejor) for m in modelos}})
        crudo.append({"Link": r["Link"], **v})
    g = glob[met]
    hay = {m: x for m, x in g.items() if pd.notna(x)}
    mejor = min(hay, key=hay.get)
    filas.append({"Link": "<b>GLOBAL</b>", **{m: neg(val(g[m]), m == mejor) for m in modelos}})
    filas.append({"Link": "nº enlaces", **{m: str(glob["n"][m]) for m in modelos}})
    filas.append({"Link": "% gana ARIMA", **{m: ("" if m == "ARIMA" else
                  f"{glob['gana'][m][met]:.1f}%") for m in modelos}})
    unidad = " (%)" if met in ("MAPE", "WAPE") else ""
    print(f"\n===== {DATASET} · {met}{unidad} por enlace · T+1 h · W={H} · modos A y B · "
          f"{len(df)} enlaces en total · negrita = mejor · -- = sin resultado =====")
    display(HTML(pd.DataFrame(filas).set_index("Link").to_html(escape=False)))
    if GUARDAR_CSV:
        os.makedirs(DIR_SALIDA, exist_ok=True)
        ruta = os.path.join(DIR_SALIDA, f"{met}_W{H}.csv")
        pd.DataFrame(crudo + [{"Link": "GLOBAL", **g}]).to_csv(ruta, index=False)


if not os.path.isdir(DIR_BASE):
    raise SystemExit(f"❌ No existe {DIR_BASE}")
for H in HORIZONTES:
    df, modelos, glob = tabla(H)
    if df is None:
        continue
    for met in METRICAS:
        mostrar(df, modelos, glob, met, H)

===== abilene · MAE por enlace · T+1 h · W=24 · modos A y B · 110 enlaces en total · negrita = mejor · -- = sin resultado =====

===== abilene · RMSE por enlace · T+1 h · W=24 · modos A y B · 110 enlaces en total · negrita = mejor · -- = sin resultado =====

===== abilene · MAPE (%) por enlace · T+1 h · W=24 · modos A y B · 110 enlaces en total · negrita = mejor · -- = sin resultado =====

===== abilene · WAPE (%) por enlace · T+1 h · W=24 · modos A y B · 110 enlaces en total · negrita = mejor · -- = sin resultado =====

   ⏭  Arch1 W168 A: no existe Results_horas_abilene/results_Arq1_1h_A_W168
   ⏭  Arch1 W168 B: no existe Results_horas_abilene/results_Arq1_1h_B_W168
   ⏭  Arch2 W168 A: no existe Results_horas_abilene/results_Arq2_1h_A_W168
   ⏭  Arch2 W168 B: no existe Results_horas_abilene/results_Arq2_1h_B_W168
   ⏭  Arch3 W168 A: no existe Results_horas_abilene/results_Arq3_1h_A_W168
   ⏭  Arch3 W168 B: no existe Results_horas_abilene/results_Arq3_1h_B_W168
   ⏭  Arch4 W168 A: no existe Results_horas_abilene/results_Arq4_1h_A_W168
   ⏭  Arch4 W168 B: no existe Results_horas_abilene/results_Arq4_1h_B_W168